AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/IndentationConsistency:
  EnforcedStyle: rails
require:
  - rubocop-rspec
  - rubocop-performance
