AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/IndentationConsistency:
  EnforcedStyle: rails
