AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
